const sharedMobileProfile = {
  width: "min(78vw, 360px)",
  height: "auto",
  justifySelf: "center",
  position: "relative",
  zIndex: "1",
};

const sharedModal = {
  overlayBackground: "rgba(12, 14, 18, 0.64)",
  contentWidth: "min(920px, calc(100vw - 32px))",
  contentHeight: "min(82vh, 820px)",
  borderRadius: "8px",
};

const minimalistTheme = {
  name: "minimalist",
  label: "Minimal",
  description: "Line study",
  primaryFont: "Montserrat, Arial, sans-serif",
  primaryColor: "#fbf8f2",
  secondaryColor: "#30333c",
  mutedColor: "#77716c",
  accentColor: "#ba6f6f",
  surfaceColor: "transparent",
  borderColor: "#181a20",
  bodyBackground: "#fbf8f2",
  background:
    "linear-gradient(90deg, rgba(24, 26, 32, 0.045) 1px, transparent 1px)",
  content: {
    maxWidth: "1180px",
    minHeight: "100vh",
    padding: "88px 56px 56px",
    gap: "30px",
    rowGap: "26px",
    alignItems: "center",
    overflow: "visible",
    backgroundSize: "96px 100%",
  },
  gridTemplate: `
    "details details details details pic pic pic pic portfolio portfolio portfolio portfolio"
    "contacts contacts contacts contacts pic pic pic pic skills skills skills skills"
  `,
  mobileGridTemplate: `
    "pic"
    "details"
    "skills"
    "portfolio"
    "contacts"
  `,
  personalDetails: {
    maxWidth: "320px",
    justifySelf: "end",
    alignSelf: "center",
    textAlign: "right",
    display: "grid",
    gap: "2px",
    padding: "0",
    background: "transparent",
    border: "0",
    borderRadius: "0",
    nameOrder: "3",
    aboutOrder: "1",
    roleOrder: "2",
    nameSize: "3rem",
    aboutSize: "1.5rem",
    roleSize: "1.2rem",
    nameWeight: "600",
    aboutWeight: "400",
    roleWeight: "400",
    nameDelay: "3s",
    aboutDelay: "2s",
    roleDelay: "2.5s",
  },
  profilePicture: {
    width: "100%",
    height: "auto",
    svgWidth: "100%",
    svgHeight: "100%",
    justifySelf: "stretch",
    alignSelf: "center",
    padding: "0",
    overflow: "visible",
    background: "transparent",
    border: "0",
    borderRadius: "0",
    boxShadow: "none",
    transform: "scale(1.14)",
    transformOrigin: "center top",
    pathStroke: "#111318",
    pathFill: "none",
    pathOpacity: "1",
    pathStrokeWidth: "1.2px",
    animationDuration: "4s",
    pathDelayOne: "0s",
    pathDelayTwo: "0.7s",
    pathDelayThree: "1.2s",
  },
  mobileProfilePicture: sharedMobileProfile,
  mobilePersonalDetails: {
    position: "relative",
    zIndex: "2",
    top: "auto",
  },
  section: {
    background: "transparent",
    border: "0",
    borderRadius: "0",
    padding: "0",
    boxShadow: "none",
  },
  skills: {
    maxWidth: "310px",
    justifySelf: "start",
    alignSelf: "start",
    textAlign: "left",
    listMaxHeight: "165px",
    overflowY: "auto",
    headingSize: "1.08rem",
    headingTransform: "none",
    headingWeight: "600",
    itemGap: "8px",
    progressHeight: "2px",
    progressBackground: "#d8a5a5",
    progressFill: "#111318",
  },
  contacts: {
    maxWidth: "320px",
    justifySelf: "end",
    alignSelf: "start",
    textAlign: "right",
    borderTop: "1px solid #111318",
    headingSize: "1.25rem",
    itemDisplay: "block",
  },
  portfolio: {
    maxWidth: "320px",
    justifySelf: "start",
    alignSelf: "end",
    textAlign: "left",
    flexDirection: "column-reverse",
    borderBottom: "1px solid #111318",
    headingSize: "1.25rem",
    itemDisplay: "block",
  },
  button: {
    background: "#ececec",
    color: "#111318",
    border: "0 solid transparent",
    borderLeft: "1px solid #111318",
    borderRight: "1px solid #111318",
    hoverBackground: "#ffffff",
    hoverColor: "#111318",
    borderRadius: "5px",
    padding: "6px 16px",
    margin: "5px",
    fontWeight: "400",
    textTransform: "none",
  },
  switcher: {
    background: "rgba(251, 248, 242, 0.92)",
    color: "#111318",
    border: "1px solid rgba(17, 19, 24, 0.18)",
    activeBackground: "#111318",
    activeColor: "#fbf8f2",
  },
  modal: {
    ...sharedModal,
    contentBackground: "#fbf8f2",
    contentColor: "#1d2028",
    border: "1px solid #111318",
  },
};

const professionalTheme = {
  name: "professional",
  label: "Studio",
  description: "Editorial card",
  primaryFont: "Georgia, 'Times New Roman', serif",
  primaryColor: "#f1ece2",
  secondaryColor: "#171717",
  mutedColor: "#6d6258",
  accentColor: "#a3422f",
  surfaceColor: "#fff9ee",
  borderColor: "#171717",
  bodyBackground: "#e5ded3",
  background:
    "linear-gradient(90deg, rgba(23, 23, 23, 0.08) 1px, transparent 1px), linear-gradient(180deg, rgba(23, 23, 23, 0.06) 1px, transparent 1px)",
  content: {
    maxWidth: "1240px",
    minHeight: "100vh",
    padding: "92px 52px 52px",
    gap: "24px",
    rowGap: "24px",
    alignItems: "stretch",
    overflow: "hidden",
    backgroundSize: "160px 160px",
  },
  gridTemplate: `
    "pic pic pic pic pic details details details details details details details"
    "pic pic pic pic pic portfolio portfolio portfolio portfolio skills skills skills"
    "contacts contacts contacts contacts contacts portfolio portfolio portfolio portfolio skills skills skills"
  `,
  mobileGridTemplate: `
    "details"
    "pic"
    "portfolio"
    "skills"
    "contacts"
  `,
  personalDetails: {
    maxWidth: "680px",
    justifySelf: "stretch",
    alignSelf: "end",
    textAlign: "left",
    display: "flex",
    flexDirection: "column",
    gap: "12px",
    padding: "32px",
    background: "#fff9ee",
    border: "1px solid #171717",
    borderRadius: "0",
    boxShadow: "10px 10px 0 #171717",
    nameOrder: "1",
    aboutOrder: "3",
    roleOrder: "2",
    nameSize: "4.1rem",
    aboutSize: "1.25rem",
    roleSize: "1rem",
    nameWeight: "700",
    aboutWeight: "400",
    roleWeight: "700",
    nameDelay: "0.15s",
    aboutDelay: "0.35s",
    roleDelay: "0.25s",
  },
  profilePicture: {
    width: "100%",
    height: "100%",
    minHeight: "620px",
    svgWidth: "130%",
    svgHeight: "auto",
    justifySelf: "stretch",
    alignSelf: "stretch",
    padding: "28px 0 0",
    overflow: "hidden",
    background: "#171717",
    border: "1px solid #171717",
    borderRadius: "0",
    boxShadow: "none",
    transform: "translateX(-11%) scale(1.08)",
    transformOrigin: "center bottom",
    pathStroke: "#f1ece2",
    pathFill: "rgba(241, 236, 226, 0.08)",
    pathOpacity: "1",
    pathStrokeWidth: "1.55px",
    animationDuration: "2.6s",
    pathDelayOne: "0s",
    pathDelayTwo: "0.18s",
    pathDelayThree: "0.32s",
  },
  mobileProfilePicture: {
    ...sharedMobileProfile,
    width: "min(86vw, 420px)",
  },
  mobilePersonalDetails: {
    position: "relative",
    zIndex: "2",
    top: "auto",
  },
  section: {
    background: "#fff9ee",
    border: "1px solid #171717",
    borderRadius: "0",
    padding: "22px",
    boxShadow: "6px 6px 0 #171717",
  },
  skills: {
    maxWidth: "100%",
    justifySelf: "stretch",
    alignSelf: "stretch",
    textAlign: "left",
    listMaxHeight: "none",
    overflowY: "visible",
    headingSize: "1rem",
    headingTransform: "uppercase",
    headingWeight: "700",
    itemGap: "12px",
    progressHeight: "8px",
    progressBackground: "#e6d8ca",
    progressFill: "#a3422f",
  },
  contacts: {
    maxWidth: "100%",
    justifySelf: "stretch",
    alignSelf: "stretch",
    textAlign: "left",
    borderTop: "1px solid #171717",
    headingSize: "1rem",
    itemDisplay: "inline-flex",
  },
  portfolio: {
    maxWidth: "100%",
    justifySelf: "stretch",
    alignSelf: "stretch",
    textAlign: "left",
    flexDirection: "column",
    borderBottom: "1px solid #171717",
    headingSize: "1rem",
    itemDisplay: "inline-flex",
  },
  button: {
    background: "#171717",
    color: "#fff9ee",
    border: "1px solid #171717",
    borderLeft: "1px solid #171717",
    borderRight: "1px solid #171717",
    hoverBackground: "#a3422f",
    hoverColor: "#fff9ee",
    borderRadius: "0",
    padding: "9px 13px",
    margin: "4px",
    fontWeight: "700",
    textTransform: "uppercase",
  },
  switcher: {
    background: "rgba(255, 249, 238, 0.94)",
    color: "#171717",
    border: "1px solid #171717",
    activeBackground: "#a3422f",
    activeColor: "#fff9ee",
  },
  modal: {
    ...sharedModal,
    contentBackground: "#fff9ee",
    contentColor: "#171717",
    border: "1px solid #171717",
  },
};

const technicalTheme = {
  name: "technical",
  label: "Systems",
  description: "Interface mode",
  primaryFont: "Consolas, 'Cascadia Mono', 'Courier New', monospace",
  primaryColor: "#071112",
  secondaryColor: "#d7fff4",
  mutedColor: "#8aa6a1",
  accentColor: "#44e0b0",
  surfaceColor: "rgba(9, 31, 34, 0.92)",
  borderColor: "#2f766f",
  bodyBackground: "#061011",
  background:
    "linear-gradient(90deg, rgba(68, 224, 176, 0.08) 1px, transparent 1px), linear-gradient(180deg, rgba(68, 224, 176, 0.07) 1px, transparent 1px), repeating-linear-gradient(135deg, transparent 0 22px, rgba(255, 207, 90, 0.06) 22px 23px)",
  content: {
    maxWidth: "1260px",
    minHeight: "100vh",
    padding: "88px 40px 40px",
    gap: "18px",
    rowGap: "18px",
    alignItems: "stretch",
    overflow: "hidden",
    backgroundSize: "34px 34px, 34px 34px, 100% 100%",
  },
  gridTemplate: `
    "details details details details pic pic pic pic portfolio portfolio portfolio portfolio"
    "skills skills skills skills contacts contacts contacts contacts portfolio portfolio portfolio portfolio"
  `,
  mobileGridTemplate: `
    "details"
    "pic"
    "skills"
    "portfolio"
    "contacts"
  `,
  personalDetails: {
    maxWidth: "100%",
    justifySelf: "stretch",
    alignSelf: "stretch",
    textAlign: "left",
    display: "flex",
    flexDirection: "column",
    gap: "10px",
    padding: "22px",
    background: "rgba(9, 31, 34, 0.92)",
    border: "1px solid #2f766f",
    borderRadius: "8px",
    boxShadow: "0 0 0 1px rgba(68, 224, 176, 0.1), 0 18px 48px rgba(0, 0, 0, 0.26)",
    nameOrder: "2",
    aboutOrder: "3",
    roleOrder: "1",
    nameSize: "2.65rem",
    aboutSize: "1.05rem",
    roleSize: "0.9rem",
    nameWeight: "700",
    aboutWeight: "400",
    roleWeight: "700",
    nameDelay: "0.18s",
    aboutDelay: "0.36s",
    roleDelay: "0.08s",
  },
  profilePicture: {
    width: "100%",
    height: "100%",
    minHeight: "520px",
    svgWidth: "118%",
    svgHeight: "auto",
    justifySelf: "stretch",
    alignSelf: "stretch",
    padding: "20px 0 0",
    overflow: "hidden",
    background:
      "linear-gradient(180deg, rgba(68, 224, 176, 0.1), rgba(9, 31, 34, 0.92))",
    border: "1px solid #2f766f",
    borderRadius: "8px",
    boxShadow: "inset 0 0 0 1px rgba(215, 255, 244, 0.06), 0 20px 52px rgba(0, 0, 0, 0.32)",
    transform: "translateX(-6%) scale(1.02)",
    transformOrigin: "center bottom",
    filter: "drop-shadow(0 0 12px rgba(68, 224, 176, 0.42))",
    pathStroke: "#44e0b0",
    pathFill: "rgba(68, 224, 176, 0.035)",
    pathOpacity: "0.96",
    pathStrokeWidth: "1.1px",
    animationDuration: "1.8s",
    pathDelayOne: "0s",
    pathDelayTwo: "0.12s",
    pathDelayThree: "0.2s",
    scanline:
      "repeating-linear-gradient(180deg, rgba(215, 255, 244, 0.06) 0 1px, transparent 1px 7px)",
  },
  mobileProfilePicture: {
    ...sharedMobileProfile,
    width: "min(84vw, 390px)",
  },
  mobilePersonalDetails: {
    position: "relative",
    zIndex: "2",
    top: "auto",
  },
  section: {
    background: "rgba(9, 31, 34, 0.92)",
    border: "1px solid #2f766f",
    borderRadius: "8px",
    padding: "18px",
    boxShadow: "0 18px 48px rgba(0, 0, 0, 0.22)",
  },
  skills: {
    maxWidth: "100%",
    justifySelf: "stretch",
    alignSelf: "stretch",
    textAlign: "left",
    listMaxHeight: "none",
    overflowY: "visible",
    headingSize: "0.94rem",
    headingTransform: "uppercase",
    headingWeight: "700",
    itemGap: "10px",
    progressHeight: "6px",
    progressBackground: "rgba(215, 255, 244, 0.12)",
    progressFill: "#44e0b0",
  },
  contacts: {
    maxWidth: "100%",
    justifySelf: "stretch",
    alignSelf: "stretch",
    textAlign: "left",
    borderTop: "1px solid #2f766f",
    headingSize: "0.94rem",
    itemDisplay: "block",
  },
  portfolio: {
    maxWidth: "100%",
    justifySelf: "stretch",
    alignSelf: "stretch",
    textAlign: "left",
    flexDirection: "column",
    borderBottom: "1px solid #2f766f",
    headingSize: "0.94rem",
    itemDisplay: "block",
  },
  button: {
    background: "rgba(68, 224, 176, 0.1)",
    color: "#d7fff4",
    border: "1px solid rgba(68, 224, 176, 0.55)",
    borderLeft: "1px solid rgba(68, 224, 176, 0.55)",
    borderRight: "1px solid rgba(68, 224, 176, 0.55)",
    hoverBackground: "rgba(255, 207, 90, 0.16)",
    hoverColor: "#ffcf5a",
    borderRadius: "4px",
    padding: "8px 10px",
    margin: "4px 0",
    fontWeight: "700",
    textTransform: "uppercase",
  },
  switcher: {
    background: "rgba(9, 31, 34, 0.94)",
    color: "#d7fff4",
    border: "1px solid #2f766f",
    activeBackground: "#44e0b0",
    activeColor: "#061011",
  },
  modal: {
    ...sharedModal,
    contentBackground: "#091f22",
    contentColor: "#d7fff4",
    border: "1px solid #2f766f",
  },
};

export const defaultTheme = minimalistTheme;

export const portfolioStyles = [
  {
    id: "minimalist",
    label: minimalistTheme.label,
    description: minimalistTheme.description,
    theme: minimalistTheme,
  },
  {
    id: "professional",
    label: professionalTheme.label,
    description: professionalTheme.description,
    theme: professionalTheme,
  },
  {
    id: "technical",
    label: technicalTheme.label,
    description: technicalTheme.description,
    theme: technicalTheme,
  },
];

export const styleTypes = portfolioStyles.map((style) => style.id);

export const themes = portfolioStyles.reduce((acc, style) => {
  acc[style.id] = style.theme;
  return acc;
}, {});

export const getPortfolioStyle = (styleId) => {
  return portfolioStyles.find((style) => style.id === styleId) || portfolioStyles[0];
};
